<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Inchirieri_Masini.WPF</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="AssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="clienti.txt" />
    <None Remove="masini.txt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="AssemblyInfo.cs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="clienti.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="masini.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LibrarieModele\LibrarieModele.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Page Update="MainWindow.xaml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Page>
  </ItemGroup>

</Project>
